name: Build Docs
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docs*
      - docs_dev/**
      - docs_user/**
      - Gemfile
      - Makefile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # this fetches all branches. Needed because we need gh-pages branch for deploy to work
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: ruby/setup-ruby@v1.160.0
        with:
          ruby-version: '3.2'

      - name: Install Asciidoc
        run: make docs-dependencies
      - name: Build user docs
        run: make docs-user
      - name: Build dev docs
        run: make docs-dev

      - name: Prepare gh-pages branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git branch -D gh-pages &>/dev/null || true
          git checkout -b gh-pages aabb4803f89a3b006094d8ae7a933650f644d036

      - name: Commit asciidoc docs
        run: |
          mv -T docs_build/adoption-user user
          mv -T docs_build/adoption-dev dev

          mv user/index-upstream.html user/index.html
          mv dev/index-upstream.html dev/index.html

          git add user
          git add dev

          mv docs_build/adoption-home/index-upstream.html index.html
          git add index.html
          git commit -m "Rendered docs"

      - name: Push rendered docs to gh-pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git push --force origin gh-pages
